# Generated by Django 4.2.10 on 2024-02-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
