# Generated by Django 4.2.10 on 2024-02-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_good_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='active',
            field=models.BooleanField(default=False, help_text='отобразить товар на сайте', verbose_name='Active'),
        ),
    ]
