# Generated by Django 4.2.10 on 2024-02-19 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_good_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='catalog.category'),
            preserve_default=False,
        ),
    ]
