# Generated by Django 4.2.10 on 2024-02-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_good_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='category',
        ),
    ]
