# Generated by Django 4.2.10 on 2024-02-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='tags',
            field=models.ManyToManyField(related_name='goods_tag', to='catalog.tag'),
        ),
    ]
