# Generated by Django 4.2.10 on 2024-02-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_good_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
